export const GET_ORDERS_COUNT          = 'GET_ORDERS_COUNT';
export const GET_ORDERS_COUNT_SUCCESS  = 'GET_ORDERS_COUNT_SUCCESS';
export const GET_ORDERS_COUNT_ERROR    = 'GET_ORDERS_COUNT_ERROR';

export const GET_STATUS_FILTER          = 'GET_STATUS_FILTER';
export const GET_STATUS_FILTER_SUCCESS  = 'GET_STATUS_FILTER_SUCCESS';
export const GET_STATUS_FILTER_ERROR    = 'GET_STATUS_FILTER_ERROR';

export const GET_ORDER_SEARCH          = 'GET_ORDER_SEARCH';
export const GET_ORDER_SEARCH_SUCCESS  = 'GET_ORDER_SEARCH_SUCCESS';
export const GET_ORDER_SEARCH_ERROR    = 'GET_ORDER_SEARCH_ERROR';